//diese file kann weg! Das ist nur um datenbank zu simmulieren!

type Item = {
  id: number;
  title: string;
  price: number;
  image: string;
  priceNoDiscount: number;
  category: string;
  size: string;
  soldLastWeek?: number;
};

const TESTITEMS: Item[] = [
  {
    id: 1,
    title: "Ring",
    price: 340,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Rings",
    size: "5",
    soldLastWeek: 10,
  },
  {
    id: 2,
    title: "Necklaces",
    price: 50,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Necklaces",
    size: "3",
    soldLastWeek: 14,
  },
  {
    id: 3,
    title: "Bracelets",
    price: 3,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Bracelets",
    size: "6",
    soldLastWeek: 17,
  },
  {
    id: 4,
    title: "Earrings",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Earrings",
    size: "8",
  },
  {
    id: 5,
    title: "Earrings",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Earrings",
    size: "5",
  },
  {
    id: 6,
    title: "Bracelets",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Bracelets",
    size: "2",
  },
  {
    id: 7,
    title: "Rings",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Rings",
    size: "5",
  },
  {
    id: 8,
    title: "Bracelets",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Bracelets",
    size: "4",
  },
  {
    id: 9,
    title: "Bracelets",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Bracelets",
    size: "5",
  },
  {
    id: 10,
    title: "Earrings",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Earrings",
    size: "3",
  },

  {
    id: 11,
    title: "Ring",
    price: 3440,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Rings",
    size: "5",
    soldLastWeek: 10,
  },
  {
    id: 12,
    title: "Necklaces",
    price: 550,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Necklaces",
    size: "3",
    soldLastWeek: 14,
  },
  {
    id: 13,
    title: "Bracelets",
    price: 36,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Bracelets",
    size: "6",
    soldLastWeek: 17,
  },
  {
    id: 14,
    title: "Earrings",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Earrings",
    size: "8",
  },
  {
    id: 15,
    title: "Earrings",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Earrings",
    size: "5",
  },
  {
    id: 16,
    title: "Bracelets",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Bracelets",
    size: "2",
  },
  {
    id: 17,
    title: "Rings",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Rings",
    size: "5",
  },
  {
    id: 18,
    title: "Bracelets",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Bracelets",
    size: "4",
  },
  {
    id: 19,
    title: "Bracelets",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Bracelets",
    size: "5",
  },
  {
    id: 20,
    title: "Earrings",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Earrings",
    size: "3",
  },

  {
    id: 21,
    title: "Ring",
    price: 340,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Rings",
    size: "5",
    soldLastWeek: 10,
  },
  {
    id: 22,
    title: "Necklaces",
    price: 50,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Necklaces",
    size: "3",
    soldLastWeek: 14,
  },
  {
    id: 23,
    title: "Bracelets",
    price: 3,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Bracelets",
    size: "6",
    soldLastWeek: 17,
  },
  {
    id: 24,
    title: "Earrings",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Earrings",
    size: "8",
  },
  {
    id: 25,
    title: "Earrings",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Earrings",
    size: "5",
  },
  {
    id: 26,
    title: "Bracelets",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Bracelets",
    size: "2",
  },
  {
    id: 27,
    title: "Rings",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Rings",
    size: "5",
  },
  {
    id: 28,
    title: "Bracelets",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Bracelets",
    size: "4",
  },
  {
    id: 29,
    title: "Bracelets",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Bracelets",
    size: "5",
  },
  {
    id: 30,
    title: "Earrings",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Earrings",
    size: "3",
  },

  {
    id: 31,
    title: "Ring",
    price: 340,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Rings",
    size: "5",
    soldLastWeek: 10,
  },
  {
    id: 32,
    title: "Necklaces",
    price: 50,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Necklaces",
    size: "3",
    soldLastWeek: 14,
  },
  {
    id: 33,
    title: "Bracelets",
    price: 3,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Bracelets",
    size: "6",
    soldLastWeek: 17,
  },
  {
    id: 34,
    title: "Earrings",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Earrings",
    size: "8",
  },
  {
    id: 35,
    title: "Earrings",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Earrings",
    size: "5",
  },
  {
    id: 36,
    title: "Bracelets",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Bracelets",
    size: "2",
  },
  {
    id: 37,
    title: "Rings",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Rings",
    size: "5",
  },
  {
    id: 38,
    title: "Bracelets",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Bracelets",
    size: "4",
  },
  {
    id: 39,
    title: "Bracelets",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Bracelets",
    size: "5",
  },
  {
    id: 40,
    title: "Earrings",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Earrings",
    size: "3",
  },

  {
    id: 41,
    title: "Ring",
    price: 340,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Rings",
    size: "5",
    soldLastWeek: 10,
  },
  {
    id: 42,
    title: "Necklaces",
    price: 50,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Necklaces",
    size: "3",
    soldLastWeek: 14,
  },
  {
    id: 43,
    title: "Bracelets",
    price: 3,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Bracelets",
    size: "6",
    soldLastWeek: 17,
  },
  {
    id: 44,
    title: "Earrings",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Earrings",
    size: "8",
  },
  {
    id: 45,
    title: "Earrings",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Earrings",
    size: "5",
  },
  {
    id: 46,
    title: "Bracelets",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Bracelets",
    size: "2",
  },
  {
    id: 47,
    title: "Rings",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Rings",
    size: "5",
  },
  {
    id: 48,
    title: "Bracelets",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Bracelets",
    size: "4",
  },
  {
    id: 49,
    title: "Bracelets",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Bracelets",
    size: "5",
  },
  {
    id: 50,
    title: "Earrings",
    price: 300,
    priceNoDiscount: 340,
    image: "/images/earrings.png",
    category: "Earrings",
    size: "3",
  },
];

export { TESTITEMS };
