import type { Metadata } from "next";
import Header from "@/components/Header";

import "./globals.css";
import HeaderShell from "@/components/smallComponents/HeaderShell";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
